/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor. 

*/ 
package com.mycompany.amnproject;

import static com.mycompany.amnproject.MainClass.con;
import static com.mycompany.amnproject.MainClass.ertek;
import static com.mycompany.amnproject.MainClass.bek;
import static com.mycompany.amnproject.ujTermekEll.számologép;
import static com.mycompany.amnproject.image.getImage;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.text.PlainDocument;


/**
 *
 * @author Crionic
 */
public class ujTermek extends javax.swing.JDialog {

   
    /**
     * Creates new form ujTermek
     */
    public ujTermek() {
        super();        
        initComponents();
        Date date =Calendar.getInstance().getTime();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String dat = df.format(date);
        Dátum.setText(dat);
        PlainDocument sz_ár = (PlainDocument) sz_ar.getDocument();
        sz_ár.setDocumentFilter(new DigitFilter()); 
        PlainDocument var = (PlainDocument) varr_ár.getDocument();
        var.setDocumentFilter(new DigitFilter()); 
        PlainDocument kell = (PlainDocument) kell_ár.getDocument();
        kell.setDocumentFilter(new DigitFilter()); 
        PlainDocument darab = (PlainDocument) db.getDocument();
        darab.setDocumentFilter(new DigitFilter());     
         try { 
            Statement st = con.createStatement();            
            ResultSet r=st.executeQuery("select Név from varró");
            while (r.next()) {  

                varr.addItem(r.getString("Név"));  
            }       
        } catch (SQLException e) {  
            JOptionPane.showMessageDialog(null,"Failed to Connect to Database","Error Connection", JOptionPane.WARNING_MESSAGE);  
            System.exit(0);  
        } 
         try {                
            Statement st = con.createStatement();
            ResultSet r=st.executeQuery("select név from szabó");

            while (r.next()) {  
                bSzab.addItem(r.getString("Név"));  
            }        
        } catch (SQLException e) {  
             System.out.println(e); 
                System.exit(0);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Dátum = new javax.swing.JTextField();
        Név = new javax.swing.JTextField();
        sz_ar = new javax.swing.JTextField();
        varr_ár = new javax.swing.JTextField();
        kell_ár = new javax.swing.JTextField();
        db = new javax.swing.JTextField();
        kom = new javax.swing.JTextField();
        btn3 = new javax.swing.JButton();
        varr = new javax.swing.JComboBox<>();
        bSzab = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Szakdolgozat");

        jLabel1.setText("Dátum");

        jLabel2.setText("Név");

        jLabel3.setText("Szabás ár");

        jLabel4.setText("varroda");

        jLabel5.setText("varroda ár");

        jLabel6.setText("kellék ár");

        jLabel7.setText("Darab szám");

        jLabel8.setText("Komment");

        jButton1.setIcon(new ImageIcon(getImage("icons/list3.png")));
        jButton1.setMaximumSize(new java.awt.Dimension(20, 20));
        jButton1.setMinimumSize(new java.awt.Dimension(20, 20));
        jButton1.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new ImageIcon(getImage("icons/megse3.png")));
        jButton2.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Dátum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DátumActionPerformed(evt);
            }
        });

        kell_ár.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kell_árActionPerformed(evt);
            }
        });

        btn3.setIcon(new ImageIcon(getImage("icons/save.png")));
        btn3.setPreferredSize(new java.awt.Dimension(20, 20));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        varr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kiválasztás" }));
        varr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varrActionPerformed(evt);
            }
        });

        bSzab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Szabász nevek:" }));
        bSzab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSzabActionPerformed(evt);
            }
        });

        jLabel10.setText("Szabász");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(361, 361, 361)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Dátum)
                                    .addComponent(sz_ar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(varr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Név)
                                    .addComponent(bSzab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(varr_ár, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kell_ár, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(db, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kom, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(115, 115, 115))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Dátum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Név, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSzab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sz_ar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(varr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(varr_ár, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kell_ár, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void kell_árActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kell_árActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kell_árActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        termek();
        
    }//GEN-LAST:event_btn3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try{    
            String m = db.getText();
            ertek = Integer.parseInt(m);
            String a = varr_ár.getText();
            int va = Integer.parseInt(a);
            String b = sz_ar.getText();
            int sz = Integer.parseInt(b);
            String d = kell_ár.getText();
            int kell = Integer.parseInt(d);
            bek = kell + sz + va;            
        }catch(NumberFormatException e){
            System.out.println(e);
        }        
        jButton1.setEnabled(false);
        java.awt.EventQueue.invokeLater(() -> {
            ujTermekEll dialog = new ujTermekEll();
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    jButton1.setEnabled(true);
                }
            });
            dialog.setVisible(true);
        });
            
         
    }//GEN-LAST:event_jButton1MouseClicked

    private void varrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varrActionPerformed
      
    }//GEN-LAST:event_varrActionPerformed

    private void DátumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DátumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DátumActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bSzabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSzabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSzabActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dátum;
    private javax.swing.JTextField Név;
    private javax.swing.JComboBox<String> bSzab;
    private javax.swing.JButton btn3;
    public static javax.swing.JTextField db;
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField kell_ár;
    private javax.swing.JTextField kom;
    private javax.swing.JTextField sz_ar;
    private javax.swing.JComboBox<String> varr;
    private javax.swing.JTextField varr_ár;
    // End of variables declaration//GEN-END:variables

    private void termek() {
        try{            
            String query = "insert into termék(Név, Dátum,szabóID, sz_ár, varróID, varr_ár, kell_ár, Mennyiség, Komment, bekerülési_költség)values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement st = con.prepareStatement(query);
            st.setString(1, Név.getText().toUpperCase());
            String text = Dátum.getText();
            java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");
            java.time.LocalDate textFieldAsDate = java.time.LocalDate.parse(text, formatter);
            java.sql.Date sqlDate = java.sql.Date.valueOf(textFieldAsDate);
            st.setDate(2, sqlDate);
            String b = sz_ar.getText();
            int sz = Integer.parseInt(b);
            st.setInt(4, sz);             
            st.setInt(3, getSzabId());             
            st.setInt(5, getVarrId());
             String a = varr_ár.getText();
            int va = Integer.parseInt(a);
            st.setInt(6, va);
            String d = kell_ár.getText();
            int kell = Integer.parseInt(d);
            st.setInt(7, kell);
            st.setDouble(8, ertek);
            st.setString(9, kom.getText().toUpperCase());            
            System.out.println(számologép);            
            double beka =  számologép;
            st.setDouble(10, beka);           
            int affectedRows = st.executeUpdate();
            if (affectedRows == 0) {
                throw new SQLException("Creating user failed, no rows affected.");
            }
        }catch(SQLException | NumberFormatException e) {
            System.out.println(e);  
        }
        
        Név.setText("");
        db.setText("");
        sz_ar.setText("");
        varr_ár.setText("");
        kom.setText("");
        kell_ár.setText("");        
    }

    public int kódSorszám() {
        int value = 0;
        try{
            //Connection conn = DriverManager.getConnection("jdbc:sqlserver://127.0.0.1;databaseName=amn;user=dsa;password=asd");
            //String query = "select Top 1 Sorszám from dbo.sorsz Order by Sorszám DESC ";
            String query = "select Top 1 Sorszám from dbo.sorsz Order by Sorszám DESC ";
            
            PreparedStatement st = con.prepareStatement(query);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                value = rs.getInt(1);
                
            }
            
        }catch(SQLException e){
            System.out.println("gond"+e);
        }
        
        return value;
    }
    
    private int getVarrId() throws SQLException {
        int id = 0;
        try{        
            String querrry = "Select id from varró where név= ?";
            PreparedStatement st = con.prepareStatement(querrry);
            String kivvar =  (String) varr.getSelectedItem();
            st.setString(1, kivvar.toUpperCase());
            ResultSet rs = st.executeQuery();
              
           while(rs.next()){
            id = rs.getInt("id");  
            System.out.println(id+ "varr");
           }  
        }
         catch (SQLException e) {  
            System.out.println(e); 
            System.exit(0);
        }return id;
    }
    private int getSzabId() throws SQLException {
        int id = 0;
        try{
            String querrry = "Select id from szabó where név= ?";
            PreparedStatement st = con.prepareStatement(querrry);
            String kivvar =  (String) bSzab.getSelectedItem();
            System.out.println(kivvar);
            st.setString(1, kivvar.toUpperCase());
            ResultSet rs = st.executeQuery();              
            while(rs.next()){
                  id = rs.getInt("id");  
                  System.out.println(id+ "szab");
           }  
        }
        catch (SQLException e) {  
            System.out.println(e); 
            System.exit(0);
        }return id;
    }

}
